### PR TITLE
assignment sol

### PR DESCRIPTION
**Pull request by vaibsharma**
Made the solution of the assignment given in the class .

### CODE REVIEW

**Comment by shubham1810** [comment]
Although you are not required to submit a pull request for these assignments, we can now do this as a regular thing for assignments. Instead of creating a file 'assignment.py' in my project root, create a directory with your name, and put the file with name 'assignment_002.py' in that.

**Comment by shubham1810** [comment]
I have created a directory called 'assignments'. create your name directory inside it and store your assignments there. send a pull request after that

**Comment by shubham1810** [comment]
you forgot to remove the assignment.py file from project root. any changes you make should be reflected only on your directory. make this change and I'll merge the PR

**Comment by vaibsharma** [comment]
Deleted assignment.py and moved it into assignments/.. directory

**Pull request merged**
